CDPTrackerSite/Models/GoalTracking/ManagerResource.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace CDPTrackerSite.Models.GoalTracking
{
    public class ManagerResource
    {
        public string sResourceName { get; set; }
        public int iResourceActiveDirectoryId { get; set; }
        public bool bResourceEvaluated { get; set; }
        public bool bResourceGoals { get; set; }
        public bool bResourceTeamMembersInput { get; set; }
        public int iManagerActiveDirectoryId { get; set; }
        //public bool bSurveyAvailable { get; set; } 
    }
}

CDPTrackerSite/Models/OnePagePlan.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace CDPTrackerSite.Models
{
    public class OnePagePlan
    {
        public List<CoreValue> core_values { get; set; }
        public List<KeyThrust> key_thrusts { get; set; }
        public List<AnnualPriority> annual_priorities { get; set; }
        public List<CriticalNumber> critical_numbers { get; set; }
        public int onePagePlanID { get; set; }

        public string SG { get; set; }
        public string G { get; set; }
        public string Y { get; set; }
        public string R { get; set; }
    }
    public class CoreValue
    {
        public int id { get; set; }
        public string core_value { get; set; }
    }

    public class KeyThrust
    {
        public int id { get; set; }
        public string key_thrust { get; set; }
    }

    public class AnnualPriority
    {
        public int id { get; set; }
        public string annual_priority { get; set; }
    }

    public class CriticalNumber
    {
        public int id { get; set; }
        public string critical_number { get; set; }
    }

   

}

CDPTrackerSite/Controllers/GoalTrackingController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Dynamic;
using System.Linq;
using System.Web.Mvc;
using CDPTrackerSite.DataAccessor;
// ReSharper disable RedundantUsingDirective ==> Directive is used when application is in Release mode 
using CDPTrackerSite.RoleManagement;
using CDPTrackerSite.Models;
using CDPTrackerSite.Models.GoalTracking;
// ReSharper restore RedundantUsingDirective
using DataSource;
using Utils;
using System.Text;
using System.Net.Mail;
using System.Net;
using System.Globalization;
using System.Configuration;
using System.DirectoryServices;
using System.Collections;
using System.IO;
using System.Data.Entity.Validation;
using System.Net.Sockets;
using CsvHelper;
using CsvHelper.Configuration;
using System.Web.Script.Serialization;
using Newtonsoft.Json;
using Antlr.Runtime;
using Newtonsoft.Json.Linq;
using CDPTrackerSite.ProfileManager;
using SelectPdf;
using Ionic.Zip;
using CDPTrackerSite.Helpers;
using System.Net.Mime;
using System.Data.SqlClient;
namespace CDPTrackerSite.Controllers
{


    public enum ProgressEnumeration
    {
        NotStarted = 0,
        InProgress = 1,
        Completed = 2,
    }

    public class GoalTrackingController : Controller
    {
        private const string SessionUserManagerName = "ManagerName";
        private const string SessionCurrentPosition = "CurrentPosition";
        private static EmployeeActiveDirectoryManager activeDirectoryInstance;
        private const string PHOTOS_URL = "https://clientes2.intelexion.com/V5TiempoDev/Fotos/";

        private const int STATUS_NOT_STARTED = 0;
        private const int STATUS_STARTED = 1;
        private const int STATUS_COMPLETED = 2;
        private const int TEAM_MEMBERS_INPUT = 1;
        private const int MANAGERS_CHECK = 2;

        CDPTrackEntities context = new CDPTrackEntities();

        /***********************************************************  Region for Helpers Methods*********************************************/
        #region Helpers

        public static IEnumerable<string> ExclusionList = new List<string>
        {
            "Jeff Jumpe",
            "Cliff Schertz",
            "itsupport",
            "Maria Pena"
        };


        public ActionResult ClickLink(int ResourceId, int id, string link, string trainingType)
        {
            try
            {
                SetupCommonViewBagValues();
                DateTime date = DateTime.Now;
                using (CDPTrackEntities context = new CDPTrackEntities())
                {
                    if (trainingType == "General")
                    {
                        GeneralTrainingProgramVisits visit = new GeneralTrainingProgramVisits { IdGeneralTrainingProgram = id, ResourceId = ResourceId, VisitDate = date };
                        context.GeneralTrainingProgramVisits.Add(visit);
                    }
                    else if (trainingType == "Training Program")
                    {
                        TrainingProgramVisits visit = new TrainingProgramVisits { IdTrainingProgram = id, ResourceId = ResourceId, VisitDate = date };
                        context.TrainingProgramVisits.Add(visit);
                    }
                    else if (trainingType == "On Demand")
                    {
                        TrainingProgramOnDemandVisits visit = new TrainingProgramOnDemandVisits { IdTrainingProgramOnDemand = id, ResourceId = ResourceId, VisitDate = date };
                        context.TrainingProgramOnDemandVisits.Add(visit);
                    }
                    context.SaveChanges();
                }
                return Content("<script language='javascript' type='text/javascript'>location.href='" + link + "'</script>");
            }
            catch (Exception ex)
            {
                ErrorLogHelper.LogException(ex, "CDPTracker");
                return Content("<script language='javascript' type='text/javascript'>location.href='" + link + "'</script>");
            }
        }

        public static EmployeeActiveDirectoryManager getActiveDirectoryInstance()
        {
            //SINGLETON PATTERN
            if (activeDirectoryInstance == null)
            {
                string activeDirectoryPath = ConfigurationManager.AppSettings["ADPath"];
                string activeDirectoryUser = ConfigurationManager.AppSettings["ADUsr"];
                string activeDirectoryPass = ConfigurationManager.AppSettings["ADPass"];
                activeDirectoryInstance = new EmployeeActiveDirectoryManager(activeDirectoryPath, activeDirectoryUser, activeDirectoryPass);
            }

            return activeDirectoryInstance;
        }

        public int? GetActiveDirectoryId()
        {
            Resource resource;
            ResourceDataAccessor.TryGetResourceByUserName(User.Identity.Name, out resource);

            if (resource.ActiveDirectoryId == null)
            {
                return 0;
            }
            else
            {
                return resource.ActiveDirectoryId;
            }
        }

        private string GetCurrentUserManagerName()
        {
            string currentUserManagerName = Session[SessionUserManagerName] as string;
            if (currentUserManagerName != null)
            {
                return currentUserManagerName;
            }

            string managerName = ResourceDataAccessor.GetManagerName(User.Identity.Name.StripDomain());
            Session[SessionUserManagerName] = managerName;

            return managerName;
        }

        public string GetCurrentPositionFromAD()
        {
            string currentPosition = Session[SessionCurrentPosition] as string;
            if (currentPosition != null)
            {
                return currentPosition;
            }

            currentPosition = ResourceDataAccessor.GetCurrentPositionFromAD(User.Identity.Name.StripDomain());
            Session[SessionCurrentPosition] = currentPosition;

            return currentPosition;
        }

        public void BaseViewBagSetup()
        {
            ViewBag.ManagerName = GetCurrentUserManagerName();
            ViewBag.CurrentPositionFromAD = GetCurrentPositionFromAD();
            ViewBag.ListOfQuarters = new SelectList(GetQuarter(), "Value", "Text", GetActualQuarter());
            ViewBag.CurrentCycle = GetCurrentCycle();

#if !DEBUG
            ViewBag.IsManager = RoleManagementHelper.UserIsInRole(User, Role.Manager);
            ViewBag.IsTalentManagementResource = RoleManagementHelper.UserIsInRole(User, Role.TalentManagement);
#else
            ViewBag.IsManager = true;
            ViewBag.IsTalentManagementResource = true;
#endif
        }

        public void SetupCommonViewBagValues()
        {
            BaseViewBagSetup();
            if (ViewBag.IsManager != true) return;

            ViewBag.PendingGoalsCount = GetManagerPendingGoalsCount();
        }

        private void SetupCommonViewBagValues(int pendingGoalsCount)
        {
            BaseViewBagSetup();
            if (ViewBag.IsManager != true) return;

            ViewBag.PendingGoalsCount = pendingGoalsCount;
        }

        private void SetProfileData(Resource resource)
        {
            int slashIndex = User.Identity.Name.IndexOf("\\", StringComparison.OrdinalIgnoreCase);
            ViewBag.userName = slashIndex >= 0 ? User.Identity.Name.Substring(slashIndex + 1).ToUpper() : User.Identity.Name.ToUpper();
            ViewBag.PROFILE_PICTURE_URL = PHOTOS_URL + resource.ActiveDirectoryId + ".jpg";
            ViewBag.resourceName = resource.Name;
            ViewBag.resourceId = resource.ResourceId;
            ViewBag.resourceAspiringPosition = resource.Employee.AspiringPosition;
        }

        private ErrorModel ErrorHandler(int errorCode)
        {
            ErrorModel err = new ErrorModel();
            err.errcode = errorCode;
            err.message = context.AppError.Where(e => e.errcode == errorCode).Select(e => e.message).FirstOrDefault();
            if (err.message == null)
            {
                err.errcode = 400;
                err.message = "Bad request";
            }
            Response.StatusCode = err.errcode;
            return err;
        }

        protected string GetManager(string domainName, IEnumerable<EmployeeActiveDirectoryManager.UserData> userDataList)
        {
            string managerName = userDataList.Where(u => string.Compare(u.DomainName, domainName, StringComparison.OrdinalIgnoreCase) == 0).Select(u => u.Manager).FirstOrDefault();
            if (managerName == null) return string.Empty;

            return managerName.GetNameFromCommonNameMatch();
        }

        private List<string> GetManagersNames()
        {
            var managers = (from mngr in context.Resources
                            join empl in context.Employee on mngr.ActiveDirectoryId equals empl.ManagerId
                            //group mngr by mngr.Name into mngrName
                            select mngr.Name).Distinct();
            //EmployeeActiveDirectoryManager employeeActiveDirectoryManager = GoalTrackingController.getActiveDirectoryInstance();
            //IEnumerable<EmployeeActiveDirectoryManager.UserData> userDataList = employeeActiveDirectoryManager.GetUserList();
            //List<string> managerNames = userDataList.GroupBy(m => m.Manager).Select(grp => grp.First().Manager.GetNameFromCommonNameMatch()).OrderBy(m => m).Where(m => !string.IsNullOrWhiteSpace(m)).ToList();
            //return managerNames;
            return managers.ToList();
        }

        private int GetManagerPendingGoalsCount()
        {
            // ReSharper disable RedundantAssignment
            string managerName = User.Identity.Name.StripDomain();

            // ReSharper restore RedundantAssignment

#if DEBUG

            //managerName = "cdptracker manager";
            //managerName = "francisco ponce";
#endif
            Resource manager;

CDPTrackerSite/Views/GoalTracking/BulkEdit.cshtml
 <!DOCTYPE html>
@model DataSource.Resource

@{
    ViewBag.Title = "Bulk Edition of the Goal List";
}

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm())
{
    @Html.HiddenFor(model => Model.ResourceId)
    <table style="width: 100%;">
        <tr>
            <th>@Html.LabelFor(model => model.GoalTrackings.FirstOrDefault().Goal)
            </th>
            <th style="text-align: center;">@Html.LabelFor(model => model.GoalTrackings.FirstOrDefault().ObjectiveId)                                         
            </th>
            <th style="text-align: center;">@Html.LabelFor(model => model.GoalTrackings.FirstOrDefault().Progress)
            </th>
            <th style="text-align: center;">@Html.LabelFor(model => model.GoalTrackings.FirstOrDefault().TrainingCategory)
            </th>
            <th style="text-align: center;">@Html.LabelFor(model => model.GoalTrackings.FirstOrDefault().TDU)
            </th>
            <th style="text-align: center;">@Html.LabelFor(model => model.GoalTrackings.FirstOrDefault().Sources)
            </th>
            <th style="text-align: center;">@Html.LabelFor(model => model.GoalTrackings.FirstOrDefault().FinishDate)
            </th>
            <th style="text-align: center;">@Html.LabelFor(model => model.GoalTrackings.FirstOrDefault().VerifiedByManager)
            </th>
            <th style="text-align: center;">@Html.LabelFor(model => model.GoalTrackings.FirstOrDefault().LastUpdate)
            </th>            
        </tr>
        <tr>
            @Html.EditorFor(model => model.GoalTrackings)
        </tr>
    </table>
    <p>
        <input type="submit" value="Save" />
    </p>
}

<div>
    <a href="@Url.Action("Index", "GoalTracking")">
        <imgsrc="@Url.Content("~/Content/images/BackTiempoButtonWB.jpg")" height="25" width="25" title="Back to List" style="border: none" />
    </a>
</div>

CDPTrackerSite/Views/GoalTracking/ConfigurationAddSurvey.cshtml
@{
    ViewBag.Title = "ConfigurationTeamMembersInput";
}
<div class="pageDescription">
    <div class="row">
        <h2>@ViewBag.SurveyText - Survey configuration</h2>
        <div>
            <p>Configure the Team Members Input survey access, you can update the DB to get a new survey for a specific quarter</p>
        </div>
    </div>
    <p>

    </p>
    <div class="row">
        <div class="col-md-12">
            <button id="addSurveyBtn" type="button" class="btn btn-success">Add New Survey Data</button>
        </div>
    </div>
    <p>

    </p>
    <div class="employeeGoalsContainer panel-group">
        <div class="employeeGoals panel panel-default">
            <div class="panel-heading">
                <h4 class="panel-title">
                    <p class="text-center"> Available Survey Data </p>
                </h4>
            </div>
            <div class="panel-body">
                <table id="surveysTable" class="table table-responsive table-hover ">
                    <thead>
                        <tr>
                            <th data-column-id="cycle">Cycle</th>
                            <th data-column-id="enabledDate">Enabled Date</th>
                            <th data-column-id="title">Survey Title</th>
                        </tr>
                    </thead>
                    <tbody>

                        @foreach (var survey in Model[0])
                        {
                            <tr>
                                <td>Q@(survey.Quarter) @survey.Year</td>
                                <td>@survey.CreatedTimeStamp.ToShortDateString()</td>
                                <td>@ViewBag.SurveyText Q@(survey.Quarter) @survey.Year</td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <p>

    </p>

    @*This div is used as a container for the available cycle options that were calculated on server side, thats the reason why it's hidden
        the generated drop down list will be added dinamycally to the table when required*@
    <div id="availableQuartersHiddenDiv" style="visibility: hidden">
        <select id="availableQuarters" class="cbCoreValue form-control">
            @foreach (var quarter in Model[1])
            {
                <option value="@quarter.Value"> @quarter.Text </option>
            }
        </select>
    </div>
</div>

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.5.0/css/bootstrap-datepicker3.min.css">
<script type='text/javascript' src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.5.0/js/bootstrap-datepicker.min.js"></script>
<script type='text/javascript'>
    // flag to identify is we are currently adding a new survey
    var isCurrentlyAdding = false;
    $(function () {
        $('#surveysTable').on('focus', '.input-group.date', function () {
            $(this).datepicker({
                calendarWeeks: true,
                todayHighlight: true,
                autoclose: true,
                orientation: 'bottom',
                startDate: '+0d'
            });
        });

        $('#surveysTable').on('click', '#addSurveyBtn', function () {
            // validate the required data is selected by the user
            if ($("#datetxt").val() === '') {
                alert('Please select a date to enable the survey.');
                return;
            }

            var surveyType = '@ViewBag.SurveyType';

            var data = {
                Cycle: $("#availableQuarters").val(),
                Type: surveyType,
                EnableDate: $("#datetxt").val()
            };

            $.ajax({
                type: "post",
                url: "AddNewSurvey",
                data: { data: JSON.stringify(data) },
                success: function (result) {
                    if (result.success) {
                        console.log(result.message);
                    }
                    else {
                        console.log(result.message);
                        alert('Something went wrong when updating the DB, please try again.');
                    }
                },
                error: function () {
                    alert('Something went wrong when updating the DB, please try again.');
                }
            });

            // once the update to the DB is ready just reload this view
            window.location.reload();
        });

        $('#surveysTable').on('click', '#cancelAddSurveyBtn', function () {
            // add operation was cancelled
            console.log('Add new survey operation cancelled.')
            window.location.reload();
        });
    });

    $("#addSurveyBtn").click(function () {
        if (!isCurrentlyAdding) {
            var cycleSelectionHtmlCode = $('#availableQuartersHiddenDiv').html();

            var dateTimePickerHtmlCode = '<div class="row">' +
                                            '<div class="col-sm-6">' +
                                                '<div class="form-group">' +
                                                    '<div class="input-group date" id="datetimepicker1">' +
                                                        '<input id="datetxt" type="text" class="form-control" />' +
                                                        '<span class="input-group-addon">' +
                                                            '<span class="glyphicon glyphicon-calendar"></span>' +
                                                        '</span>' +
                                                    '</div>' +
                                                '</div>' +
                                            '</div>' +
                                         '</div>';

            var saveDataBtnHtmlCode = '<button id="addSurveyBtn" type="button" class="btn btn-success">Save Data</button>';

            var cancelBtnHtmlCode = '<button id="cancelAddSurveyBtn" type="button" class="btn btn-danger">  Cancel  </button>';

            var rowToAddSurvey = '<tr>' +
                                    '<td>' +
                                        cycleSelectionHtmlCode +
                                    '</td>' +
                                    '<td>' +
                                        dateTimePickerHtmlCode +
                                    '</td>' +
                                    '<td>' +
                                        saveDataBtnHtmlCode +
                                        '<div style="width:10px; height:auto; display:inline-block;"/>' +
                                        cancelBtnHtmlCode +
                                    '</td>' +
                                 '</tr>';
            $('#surveysTable').append(rowToAddSurvey);

            // disabling the add new survey data button
            isCurrentlyAdding = true;
        }
        else {
            console.log('Already started to add a new survey data, please complete this task first.');
        }
    });

</script>

CDPTrackerSite/Views/GoalTracking/Create.cshtml
 <!DOCTYPE html>

@model DataSource.GoalTracking

@{
    ViewBag.Title = "Create New Goal";
}

@if (ViewBag.message != null)
{
    <script type='text/javascript'>alert('Please choose a training category.');</script>                              
}

<h2>@ViewBag.Title</h2>
<style type="text/css">
  table{
    border-collapse: collapse;
    border: 0;
  }
  table td{
    border: 0;
  }
</style>
<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

<script type ="text/javascript">
    $(document).ready(function () {
        var dropdown = document.getElementById("trainingCategory")
        var textbox = document.getElementById("TDUs2")
        var description = document.getElementById("description")
        $("#trainingCategory").change(function () {
            switch (dropdown.value) {
                case "1":
                    description.textContent = '@ViewBag.Description[0]'
                    textbox.max = '@ViewBag.MaxTDU[0]'
                    textbox.value = '@ViewBag.TDU[0]'
                    break;
                case "2":
                    description.textContent = '@ViewBag.Description[1]'
                    textbox.max = '@ViewBag.MaxTDU[1]'
                    textbox.value = '@ViewBag.TDU[1]'
                    break;
                case "3":
                    description.textContent = '@ViewBag.Description[2]'
                    textbox.max = '@ViewBag.MaxTDU[2]'
                    textbox.value = '@ViewBag.TDU[2]'
                    break;
                case "4":
                    description.textContent = '@ViewBag.Description[3]'
                    textbox.max = '@ViewBag.MaxTDU[3]'
                    textbox.value = '@ViewBag.TDU[3]'
                    break;
                case "5":
                    description.textContent = '@ViewBag.Description[4]'
                    textbox.max = '@ViewBag.MaxTDU[4]'
                    textbox.value = '@ViewBag.TDU[4]'
                    break;
                case "6":
                    description.textContent = '@ViewBag.Description[5]'
                    textbox.max = '@ViewBag.MaxTDU[5]'
                    textbox.value = '@ViewBag.TDU[5]'
                    break;
                default:
                    description.textContent = "Please select a training category to show its description";
                    textbox.value = 0;
            }
        })
        $("#sourceOption").change(function () {
            var sourceText = document.getElementById("sourceText");
            var source = document.getElementById("source");
            var sourceDropdown = document.getElementById("sourceOption");
            if (sourceDropdown.value == "0") {
                sourceText.style.display = 'block';
                source.style.display = 'block'
            }
            else {
                sourceText.style.display = 'none';
                source.style.display = 'none';
            }
        })
    })
</script>

@using (Html.BeginForm())
{
    @Html.ValidationSummary(true)
    <fieldset>
        <legend>Goal Tracking</legend>
        <div style="float:right; max-width: 300px">
            <b>Mastery Objective Thinking:</b>
            <span>
            <br/>
            What exactly do I want to know and be able to do when the quarter is over?
            <br/><br/>
            How can my manager know that I have learned?
            <br/><br/>
            What kind of evidence can be provided?
            <br /><br/>
            </span>
            <span><b>Please consider</b>
                <br/>
                Is the objective worded so that the learning target is clear for me and my manager?
                <br/><br/>                
                Is the the objective worth knowing/learning?
                <br/><br/>
                Is the objective challenging and attainable?
                <br/><br/>
                Is the objective able to be assessed and measured?
                <br/><br/>
            </span>
        </div>
        @Html.HiddenFor(m => m.ResourceId)
        <div class="editor-label">
            <table id="editGoalTable">
                <tr>
                    <td>
                        @Html.LabelFor(model => model.Goal)
                    </td>
                </tr>
                <tr>
                    <td>
                        @Html.TextBoxFor(model => model.Goal, new { style = "width:500px", autocomplete = "off" })
                        @Html.ValidationMessageFor(model => model.Goal)
                    </td>
                </tr>
                <tr>
                    <td>
                        Training Category
                    </td>
                </tr>
                <tr>
                    <td>
                        @Html.DropDownListFor(model => model.TrainingCategoryId, new SelectList(ViewBag.ListOfCategories2, "Value", "Text"), "Please select a category", new { required = "required", @id = "trainingCategory", @name = "trainingCategory", @runat = "server" })
                    </td>
                </tr>
                <tr>
                    <td>
                        Description
                    </td>
                </tr>
                <tr>
                    <td>
                        <label id="description">Please select a training category to show its description</label>
                    </td>
                </tr>
                </table>
            <table>
                <tr>
                    <td>
                        Source
                    </td>
                    <td id="sourceText" style="display:none">
                        Specify
                    </td>
                </tr>
                <tr>
                    <td>
                        @Html.DropDownListFor(model => model.SourceId, new SelectList(ViewBag.ListOfSources2, "Value", "Text"), "Please select a source", new { required = "required", id = "sourceOption" })      
                    </td>
                    <td>     
                        <input id="source" name="source" style="display:none; height:20px" required></>
                    </td>
                </tr>
                </table>
            <table>
                <tr>
                    <td>
                        TDUs
                    </td>
                </tr>
                <tr>
                    <td>
                        <input id="TDUs2" type="number" name="TDUs2" min="0"></>
                    </td>
                </tr>
                <tr>
                    <td>
                        Finish By
                    </td>
                </tr>
                <tr>
                    <td>
                        @Html.TextBoxFor(model => model.FinishDate, new { @class = "date", @readonly = "readonly" })            
                        @Html.ValidationMessageFor(model => model.FinishDate)
                    </td>
                </tr>
            </table>   
        </div>
        <p>
            <input type="submit" value="Create"/>
        </p>
    </fieldset>
    <p>
        <a href="@Url.Action("Index", "GoalTracking")">
            <img src="@Url.Content("~/Content/images/BackTiempoButtonWB.jpg")" height="25" width="25" title="Back to My Goals" style="border: none" />
        </a>
    </p>
}

CDPTrackerSite/Views/GoalTracking/DeleteAssessment.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@model DataSource.Assessment
<h2>Delete Asessment</h2>

<h3>Are you sure you want to delete this Assessment?</h3>
@using (Html.BeginForm("DeleteAssessmentConfirmed", "GoalTracking",FormMethod.Post))
{
    @Html.HiddenFor(x=>x.AssessmentId)
    <fieldset>
        <legend>Details</legend>
        <div class="display-label"><b>Description:</b> @Html.DisplayFor(model => model.Description)</div>
        <div class="display-label"><b>Term:</b> @Html.DisplayFor(model => model.TermProperty.Name)</div>
        <p>
            <input type="submit" value="Delete" />
        </p>
    </fieldset>
}
<div>
    <a href="@Url.Action("SelfAssessment", "GoalTracking")">
        <img src="@Url.Content("~/Content/images/BackTiempoButtonWB.jpg")" height="25" width="25" title="Back to List" style="border: none" />
    </a>
</div>

CDPTrackerSite/Views/GoalTracking/EditTrainingProgramCategory.cshtml
@model DataSource.TrainingProgramCategory
@{
    ViewBag.Title = "Edit Training Program Category";
}

<style type="text/css">
    table {
        border-collapse: collapse;
        border: 1px solid #ddd;
    }

        table td {
            border: 1px solid #ddd;
        }
</style>

<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>

<script type="text/javascript">
    $(document).ready(function () {
        $("#Name").keyup(function () {
            if ($('#Name').val() == "") {
                document.getElementById("name").innerHTML = "The Training Program Category field cannot be empty";
            }
            else {
                document.getElementById("name").innerHTML = "";
            }
        });
    });
</script>
<div class="pageDescription">
    <div class="description">
        <h2>@ViewBag.Title</h2>
        @using (Html.BeginForm())
        {
            @Html.ValidationSummary(true)
            <fieldset>
                
                @Html.HiddenFor(m => m.IdTrainingProgramCategory)
                
                <div class="editor-label">
                    @Html.Label("Training Program Category")
                </div>
                <div class="editor-field">
                    @Html.TextBoxFor(model => model.Name, new { style = "width:500px", required = "required", autocomplete = "off" })
                    @Html.ValidationMessageFor(model => model.Name)
                </div>
                <div>
                    <label id="name" style="color: red;"></label>
                </div>

                @if (ViewBag.error != "")
                {
                    <p style="color: #FF0000; font-size: medium;"><strong>@ViewBag.error</strong></p>
                }

                <p>
                    <input type="submit" id="btnSave" value="Save" />
                </p>
            </fieldset>
            
        }
    </div>
</div>